'use strict';

module.exports = {
  DEFAULT_PROTOCOL: `http`,
  DEFAULT_DOMAIN: `localhost`,
  DEFAULT_FRONTEND_PORT: 8080,
  DEFAULT_BACKEND_PORT: 3000,
  DEFAULT_LOG_LEVEL: `info`,
  DEFAULT_DB_DRIVER: `postgres`,
  JWT_ACCESS_SECRET_DEFAULT: `access`,
  JWT_REFRESH_SECRET_DEFAULT: `refresh`,
  MAX_AGE_ACCESS_TOKEN_COOKIE: 900000,
  MAX_AGE_REFRESH_TOKEN_COOKIE: 86400000,
};
